name: CI

env: 
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo fmt --all -- --check

  tests-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install libudev
      run: sudo apt-get install libudev-dev
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test 
    - name: Generate code coverage with tarpaulin
      run: |
        cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Install libudev
      run: sudo apt-get install libudev-dev
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo clippy -- -D warnings
